#' Initialize gitpod configuration
#'
#' @description
#' Initializes `.gitpod.Dockerfile` and `.gitpod.yml` at the working directory
#' with the necessary gitpod configuration information
#'
#' @param apt_packages Additional `apt` packages to install in the Docker image.
#' @param user_code User code to configure in `.gitpod.yml`
#'
#' @examples
#' \dontrun{
#' use_gitpod()
#' }
#' @importFrom usethis use_template
#' @export
use_gitpod <- function(apt_packages = NULL, user_code = NULL) {
  generator <- "Generated by cynkrathis::use_gitpod(), do not edit by hand"
  deparsed_apt_packages <- paste(apt_packages, collapse = " ")
  deparsed_user_code <- prepend(user_code, "      ")
  deparsed_call <- prepend(capture_call(sys.call()), "# ")

  new_gitpod_yml <- usethis::use_template(
    "gitpod.yml",
    ".gitpod.yml",
    data = list(
      generator = generator,
      user_code = deparsed_user_code,
      call = deparsed_call
    ),
    package = "cynkrathis",
    ignore = TRUE
  )

  invisible(new_gitpod_yml)
}

prepend <- function(x, prefix) {
  if (is.null(x)) {
    return("")
  }
  x_vec <- unlist(strsplit(x, "\n"))
  x_prefix <- gsub("^ *", prefix, x_vec)
  paste0(x_prefix, collapse = "\n")
}

capture_call <- function(call) {
  capture.output(print(constructive::construct(call)))
}
