#' Initialize CMakeLists configuration
#'
#' @description
#' Initializes a `CMakeLists.txt` at the current working directory and at the `src/`
#' folder with the necessary configuration information
#'
#' @param project `[character]`\cr
#'   The name of the R project
#'
#' @examples
#' \dontrun{
#' use_cmakelists("Your_Project_Name")
#' }
#' @importFrom usethis use_template
#' @importFrom fs dir_create
#' @export
use_cmakelists <- function(project = NULL) {
  generator <- "Generated by cynkrathis::use_cmakelists(), do not edit by hand"
  deparsed_call <- prepend(capture_call(sys.call()), "# ")

  if (is.null(project)) {
    project <- desc::desc_get_field("Package")
  }

  new_cmakelist <- usethis::use_template(
    "CMakeLists.txt",
    "CMakeLists.txt",
    package = "cynkrathis",
    data = list(
      generator = generator,
      call = deparsed_call,
      project = project
    ),
    ignore = TRUE
  )

  fs::dir_create("src")

  ext_files <- list.files(path = "src", pattern = "\\.(c|h|cpp)$")
  ext_files <- withr::with_collate("C", prepend(sort(ext_files), "  "))

  new_cmakelist_src <- usethis::use_template(
    "CMakeLists-src.txt",
    "src/CMakeLists.txt",
    package = "cynkrathis",
    data = list(
      generator = generator,
      call = deparsed_call,
      project = project,
      ext_files = ext_files
    ),
    ignore = FALSE
  )

  invisible(new_cmakelist || new_cmakelist_src)
}
